### ISSUE TITLE
After installation and `sudo reboot` I just end up at a terminal screen

### ISSUE THREAD

**Issue by Fusty** [AllGray/PocketDesk#1]
I get a prompt for 
```
Debian GNU/Linux 8 PocketDESK tty1

PocketDESK login:
```

For which my username and password combo work.  However it is just a terminal.  I re-ran the installer from this shell, rebooted and it is the same story.  I haven't done much to my pocketCHIP so I can hardly assume it is out of date.  Especially since this repo was update within the last 18 days.  

If you have any insight, or have had this occur to yourself during development I'd appreciate any help you may lend me!

**Comment by Fusty** [comment]
`startx` complains there are no screens.  Xorg logs show it attempting to load module "armsoc" which fails (module does not exist, 0) as well as it complaining that No drivers are available.

**Comment by Fusty** [comment]
Ok, I reflashed.  Installed from ssh while I left my pocketCHIP on pocketHome screen.  Rebooted and things work fine.  Not sure why it didn't work the first time.  Not worried about it.

**Comment by AllGray** [comment]
I have not had that bug happen to me. Glad it worked out in the end. 

The best place for PocketDESK support is here: 
https://bbs.nextthing.co/t/introducing-pocketdesk-unify-your-pocketchip/18420
