### ISSUE TITLE
Install dependencies "Fail" every time I try to install 

### ISSUE THREAD

**Issue by ghost** [AllGray/PocketDesk#11]
Every time I try to install the normal PocketHome I always get on the "installing dependencies" part a fail. Probably it might be due to NTC's servers going down after they ceased operations. Looked in the dependencies script and inside it it had the openssource.nextthing.co when NTC was still up. Probably because the site was down it failed to install. If we could find a mirror to get the dependencies it was installing, that would be great!

**Comment by ghost** [comment]
Never mind, I got the mirrior sorted myself :)

**Comment by mladidy** [comment]
Never mind, I got the mirrior sorted myself :)

**Comment by smashedupface** [comment]
hello this is the only place that seems to mention this issue about failed dependencies .could anyone please enlighten me.
