### ISSUE TITLE
PocketHome theme (referred as window style in xfce) is not matching what is by default the chip dark theme

### ISSUE THREAD

**Issue by Adzetko** [AllGray/PocketDesk#5]
So, using PocketHome, when I launch `xfce4-appearance-settings` I see my selected style as "Chip", but when I go to any program actually supposed to use the xfce style (very noticeable in the file browser `PCManFM` for exemple), it's the default greyish win95-looking theme.

In Desktop mode (using xfce), the desktop theme is all violet and dark, like the normal Chip theme.

I think it's not a problem with the Marshmallow's fork of PocketHome because before installing PocketDesk I had the standard PocketCHIP firmware with his fork installed, and the theme manager were working  properly system-wide. Now every desktop manager except xfce does have some grayish default theme instead of the one made for PocketCHIP.

**Comment by rxvincent** [comment]
~/.gtkrc-2.0

gtk-icon-theme-name = "Faenza-Dark"
gtk-theme-name = "Chip"

**Comment by Adzetko** [comment]
@rxvincent This worked like a charm! Thanks!
